name: LpkPlayerLevelAPI
main: LamPocketVN\PlayerLevelAPI\PlayerLevelAPI
author: LamPocketVN
api: [3.11.0, 4.0.0]
version: 0.1
commands:
  plevel:
    description: PlayerLevelAPI command
permissions:
  plevel.command:
    default: op
    description: Allows use of the /plevel command
